#pragma once

#include <cstdint>

// Registered binary: client.dll (project 'client')
// Alignment: 8
// Size: 0x570
// Has VTable
// 
// MNetworkVarNames "bool m_bIsPlayingBack"
// MNetworkVarNames "bool m_bPaused"
// MNetworkVarNames "bool m_bMultiplayer"
// MNetworkVarNames "bool m_bAutogenerated"
// MNetworkVarNames "float32 m_flForceClientTime"
// MNetworkVarNames "uint16 m_nSceneStringIndex"
// MNetworkVarNames "CHandle< C_BaseFlex > m_hActorList"
class C_SceneEntity : public C_PointEntity
{
private:
	[[maybe_unused]] uint8_t __pad0510[0x8]; // 0x510
public:
	// MNetworkEnable
	bool m_bIsPlayingBack; // 0x518	
	// MNetworkEnable
	bool m_bPaused; // 0x519	
	// MNetworkEnable
	bool m_bMultiplayer; // 0x51a	
	// MNetworkEnable
	bool m_bAutogenerated; // 0x51b	
	// MNetworkEnable
	// MNetworkChangeCallback "OnResetClientTime"
	float m_flForceClientTime; // 0x51c	
	// MNetworkEnable
	// MNetworkPriority "32"
	uint16_t m_nSceneStringIndex; // 0x520	
	bool m_bClientOnly; // 0x522	
private:
	[[maybe_unused]] uint8_t __pad0523[0x1]; // 0x523
public:
	CHandle< C_BaseFlex > m_hOwner; // 0x524	
	// MNetworkEnable
	// MNetworkPriority "32"
	C_NetworkUtlVectorBase< CHandle< C_BaseFlex > > m_hActorList; // 0x528	
	bool m_bWasPlaying; // 0x540	
private:
	[[maybe_unused]] uint8_t __pad0541[0xf]; // 0x541
public:
	CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents; // 0x550	
	float m_flCurrentTime; // 0x568	
};

