#pragma once

#include <cstdint>

// Registered binary: server.dll (project 'server')
// Enumerator count: 10
// Alignment: 4
// Size: 0x4
enum class AI_FacingTargetRequestSource_t : uint32_t
{
	eInvalid = 0xffffffffffffffff,
	// MPropertyFriendlyName "Motor"
	eMotor = 0x0,
	// MPropertyFriendlyName "Choreo"
	eChoreo = 0x1,
	// MPropertyFriendlyName "LevelScript"
	eLevelScript = 0x2,
	// MPropertyFriendlyName "SmartGoal"
	eSmartGoal = 0x3,
	// MPropertyFriendlyName "Schedule"
	eSchedule = 0x4,
	// MPropertyFriendlyName "Navigator"
	eNavigator = 0x5,
	// MPropertyFriendlyName "Autogenerated"
	eAutogenerated = 0x6,
	// MPropertyFriendlyName "Ahead"
	eAhead = 0x7,
	eCount = 0x8,
};

